import { useState } from 'react'
import type { ComponentCard, Report as ReportData } from '../lib/api'
import type { BikeShop } from '../lib/shops'
import ShopFinder from './ShopFinder'

interface Props {
  report: ReportData
  onBack: () => void
}

const BIKE_LABEL: Record<string, string> = {
  road: 'Road bike',
  gravel: 'Gravel bike',
  mtb: 'Mountain bike',
}

const CONDITIONS_LABEL: Record<string, string> = {
  dry: 'mostly dry',
  mixed: 'mixed',
  wet: 'often wet',
}

function usageLine(card: ComponentCard): string {
  const unit = card.unit === 'miles' ? 'miles' : 'months'
  const lo = card.interval_lo.toLocaleString()
  const hi = card.interval_hi.toLocaleString()
  const range = card.interval_lo === card.interval_hi ? lo : `${lo}–${hi}`
  return `~${Math.round(card.used).toLocaleString()} ${unit} on it (service interval ${range} ${unit})`
}

export default function WorkOrder({ report, onBack }: Props) {
  const [shop, setShop] = useState<BikeShop | null>(null)
  const overdue = report.cards.filter((c) => c.status === 'overdue')
  const dueSoon = report.cards.filter((c) => c.status === 'due_soon')
  const today = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <section className="work-order">
      <div className="wo-actions no-print">
        <button onClick={onBack}>← Back to report</button>
        <button className="primary" onClick={() => window.print()}>
          Print / Save PDF
        </button>
      </div>

      <div className="wo-sheet">
        <header className="wo-header">
          <div>
            <h2>Shop Work Order</h2>
            <p className="wo-sub">Bike Health Report · {today}</p>
          </div>
          <div className="wo-meta">
            <p>{BIKE_LABEL[report.bike_type] ?? report.bike_type}</p>
            <p>
              {Math.round(report.total_miles).toLocaleString()} miles logged ·{' '}
              {CONDITIONS_LABEL[report.conditions] ?? report.conditions} conditions
            </p>
            {shop && (
              <p className="wo-shop">
                For: <strong>{shop.name}</strong>
                {shop.address ? ` · ${shop.address}` : ''}
              </p>
            )}
          </div>
        </header>

        <p className="wo-intro">
          Please inspect the items below. Estimated wear comes from the rider's logged mileage
          — your eyes on the bike are the final word.
        </p>

        {overdue.length > 0 && (
          <>
            <h3 className="wo-section overdue-h">Likely due now</h3>
            <ul className="wo-list">
              {overdue.map((c) => (
                <li key={c.key}>
                  <span className="wo-box" aria-hidden="true" />
                  <div>
                    <strong>{c.label}</strong> — inspect &amp; replace
                    <p className="wo-detail">{usageLine(c)}</p>
                  </div>
                </li>
              ))}
            </ul>
          </>
        )}

        {dueSoon.length > 0 && (
          <>
            <h3 className="wo-section due-h">Coming up — check while it's in the stand</h3>
            <ul className="wo-list">
              {dueSoon.map((c) => (
                <li key={c.key}>
                  <span className="wo-box" aria-hidden="true" />
                  <div>
                    <strong>{c.label}</strong> — inspect
                    <p className="wo-detail">{usageLine(c)}</p>
                  </div>
                </li>
              ))}
            </ul>
          </>
        )}

        {overdue.length === 0 && dueSoon.length === 0 && (
          <p className="wo-clear">
            Nothing urgent — this bike is in good shape. A general safety check is never wasted.
          </p>
        )}

        <footer className="wo-footer">
          <p>
            Notes / additional findings: <span className="wo-line" />
          </p>
          <p className="wo-credit">Generated by Bike Health Report from the rider's own ride log.</p>
        </footer>
      </div>

      <ShopFinder selected={shop} onSelect={setShop} />
    </section>
  )
}
